language: c
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install texinfo libxml2-dev check libgcrypt11-dev dpkg-dev devscripts

script:
  - ./autogen.sh
  - ./configure CFLAGS='-g -fmessage-length=0 -pedantic -std=gnu99 -Wall -Wextra -Wwrite-strings -Winit-self -Wcast-align -Wcast-qual -Wpointer-arith -Wstrict-aliasing -Wformat=2 -Wmissing-declarations -Wmissing-include-dirs -Wno-unused-parameter -Wuninitialized -Wold-style-definition -Wstrict-prototypes -Wmissing-prototypes -Wshadow'
  - make
  - make clean
  - ./configure --enable-deb
  - make check
  - make deb
